### ISSUE TITLE
Add Lobster subtree

### ISSUE THREAD

**Issue by kriskowal** [borkshop/lobsterquest#1]

**Comment by jcorbin** [comment]
Can we do a subtree merge instead please? Would rather be able to patch upstream code at will and/or not have to update a submodule over the internet in a follow up command?

**Comment by kriskowal** [comment]
Subtree is great. If you get to this before me, perhaps leave a `scripts/update-lobster`. I find that subtree updates are weird enough I have to rediscover them each time I need to do one.
