### ISSUE TITLE
Managing Generated Code Assets

### ISSUE THREAD

**Issue by jcorbin** [borkshop/lobsterquest#15]
So #12 made a decision to stop checking in generated code assets.

Can we please stop that, and check in the sheet code again?

Especially for code that's relatively intrinsic, but even I'd argue let's check in sufficient assets to always be able to build the game in the future, without any access to external resources ( Google Sheets not least of all ;-) )

Related: can we please stop using unix-specific ( or at least -more-friendly ) tooling for project automation, and just rely on Go and/or Lobster?

**Comment by kriskowal** [comment]
Checking in assets is fine.

Removing bash entirely? I’ve never found a good compromise that works for both Windows and Unices, except of course WSL. You down for making `.bat` files that sit next to `.sh` files?

**Comment by kriskowal** [comment]
Assets are now checked in. Management instructions are in README except for the openmoji update script which is still better served by the script. We can port it to .bat if we ever need to run it again on Windows but otherwise updates should be rarely needed.
