### ISSUE TITLE
Migrate code from Lobster forks

### ISSUE THREAD

**Issue by kriskowal** [borkshop/lobsterquest#4]
Emoji Quest code currently resides on a `moji` branch on `kriskowal/lobster` and `jcorbin/lobster`.

**Comment by kriskowal** [comment]
@jcorbin Let me know if you’d like to seize this one and #1.

**Comment by jcorbin** [comment]
Yes happy to do, but I really want to "finish" the entity graph mechanics out first, more towards #7? So happy if you beat me to these...

**Comment by kriskowal** [comment]
Okay. I’ve done #1 and I’ll go ahead and integrate the code from `kriskowal/moji`. I assume that your work on entity graphs is sufficiently disjoint that it will be easy to migrate separately.

**Comment by kriskowal** [comment]
Completed with #10, #11, & #12. I managed to preserve history on the evolution of the Lobster code.
